### ISSUE TITLE
metadata.yaml formatting errors

### ISSUE THREAD

**Issue by dhimmel** [trang1618/tpot-ds-ms#1]
The [build failed](https://travis-ci.org/trang1618/tpot-ds-ms/builds/446850879) for https://github.com/trang1618/tpot-ds-ms/commit/570d0929c02e897b0e1dca3adfc0590cc74321f6 seemingly due to YAML formatting issue:

```
yaml.scanner.ScannerError: while scanning a simple key
  in "content/metadata.yaml", line 18, column 1
could not find expected ':'
  in "content/metadata.yaml", line 20, column 11
```

The following parts look problematic to me:

https://github.com/trang1618/tpot-ds-ms/blob/570d0929c02e897b0e1dca3adfc0590cc74321f6/content/metadata.yaml#L16-L18

https://github.com/trang1618/tpot-ds-ms/blob/570d0929c02e897b0e1dca3adfc0590cc74321f6/content/metadata.yaml#L26-L28

Specifically the newline before `Pennsylvania`

**Comment by dhimmel** [comment]
Nice fix.

Since the build passed, the manuscript was deployed at https://trang1618.github.io/tpot-ds-ms/v/28098cb38b80422c1d995af08e7557be93db757e/. You'll see that now has the updated author info.

**Comment by trangdata** [comment]
Yes I see it! Thank you @dhimmel!
