### ISSUE TITLE
Update thumbnail

### ISSUE THREAD

**Issue by vincerubinetti** [trang1618/tpot-ds-ms#12]
Hello Manubot user.

If you were not already aware, your paper is being showcased in the [Manubot Catalog](https://manubot.org/catalog/).

Previously, we were making our own thumbnails for each paper, and hosting them in the same repository as `manubot.org`. But now we are moving to a system of having each paper store its thumbnail in its own repository, and linking to it from there.

Here is our suggested thumbnail for your paper that follows the new [thumbnail guidelines](https://github.com/manubot/catalog#thumbnail-guidelines):

![New Project (1)](https://user-images.githubusercontent.com/8326331/64822291-b1628780-d582-11e9-9e0e-06c35d482e81.png)

Please place this image *in the root of your repository* with the name `thumbnail.png`. Once you have, let us know in this issue and we'll do the rest to update the catalog.

**Comment by trangdata** [comment]
@vincerubinetti  completed in [this commit](https://github.com/trang1618/tpot-fss-ms/commit/d0de3ece81d493d84e9e26e58f4cd1f62cca6e58).
